//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int userId { get; set; }
        public int creditId { get; set; }
        public string creditNum { get; set; }
        public string creditNameUser { get; set; }
        public string cvv { get; set; }
        public string t_z { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
