//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterShift
    {
        public int shiftMasterId { get; set; }
        public int cardMasterId { get; set; }
        public int dayOfWeek { get; set; }
        public double fromHour { get; set; }
        public double untillHour { get; set; }
    
        public virtual CardMaster CardMaster { get; set; }
    }
}
