//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        public int meetingId { get; set; }
        public int userId { get; set; }
        public int userId_master { get; set; }
        public System.DateTime dateMeeting { get; set; }
        public int categoryId { get; set; }
        public Nullable<int> kind_level { get; set; }
        public Nullable<int> availability_level { get; set; }
        public Nullable<int> mastery_level { get; set; }
        public string describeText { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
